# Generated by Django 3.1.2 on 2020-10-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housepub',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
